# File: azure-pipelines.yml

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pr:
  branches:
    include:
    - master
    - develop
  paths:
    exclude:
    - README.md

jobs:

- template: templates/brew_test_bot.yml
  parameters:
    name: brew_test_bot_macOS_10_13
    displayName: Create bottles for macOS High Sierra (10.13)
    vmImage: macOS-10.13

- template: templates/brew_test_bot.yml
  parameters:
    name: brew_test_bot_macOS_10_14
    displayName: Create bottles for macOS High Mojave (10.14)
    vmImage: macOS-10.14

# - job: brew_test_bot_macOS_10.14
#   displayName: "Create bottles for macOS High Mojave (10.14)"

#   pool:
#     vmImage: macOS-10.14

#   strategy:
#     maxParallel: 8
#     matrix:
#       hello-world:
#         package: hello-world


# - job: brew_test_bot_ci_upload
#   displayName: "Upload bottles"

#   pool:
#     vmImage: macOS-10.14
