# File: azure-pipelines.yml

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pr:
  branches:
    include:
    - master
    - develop
  paths:
    exclude:
    - README.md

stages:

  - stage: brew_test_bot
    displayName: Create bottles

    jobs:
      - template: templates/brew_test_bot.yml
        parameters:
          name: brew_test_bot_macOS_10_13
          displayName: for macOS High Sierra (10.13)
          vmImage: macOS-10.13

      - template: templates/brew_test_bot.yml
        parameters:
          name: brew_test_bot_macOS_10_14
          displayName: for macOS High Mojave (10.14)
          vmImage: macOS-10.14


  - stage: brew_test_bot_ci_upload
    displayName: Upload bottles

    dependsOn:
      - brew_test_bot

    condition: succeeded()

    jobs:
      - template: templates/brew_test_bot_ci_upload.yml
        parameters:
          name: Upload bottles
