# File: .azure-ci/brew_test_bot.yml

parameters:
  name: ''
  displayName: ''
  vmImage: ''
  xcode: ''

jobs:

- job: ${{ parameters.name }}
  displayName: "${{ parameters.displayName }}"

  pool:
    vmImage: ${{ parameters.vmImage }}

  dependsOn: []

  variables:
    xcode_version: ${{ parameters.xcode }}
    artifact_name: ${{ parameters.vmImage }}

  steps:

    # Setup CI environment
    - template: setup-ci-env.yml
      parameters:
        xcode: $(xcode_version)

    # Install your tap
    - template: install-tap.yml

    # When working on a fork of homebrew/test-bot, run this step to tap your
    # repository and checkout the correct feature branch
    # - template: tap-dev-test-bot.yml

    - bash: |
        echo UPSTREAM_GIT_URL:      $(UPSTREAM_GIT_URL)
        echo UPSTREAM_PULL_REQUEST: $(UPSTREAM_PULL_REQUEST)
        brew test-bot --root-url=$(bintray_root_url)
      displayName: Run brew test-bot
      env:
        UPSTREAM_GIT_URL: $(UPSTREAM_GIT_URL)
        UPSTREAM_PULL_REQUEST: $(UPSTREAM_PULL_REQUEST)

    - script: |
        FORMULA="$(ls *.bottle.json | sed 's/--.*//g')"
        echo "Formula name is: $FORMULA"
        echo "##vso[task.setvariable variable=formula;isOutput=true]$FORMULA"
      displayName: Set formula variable
      name: set_formula_name

    - bash: |
        cp *.bottle.* $(Build.ArtifactStagingDirectory)
      displayName: Copy json & bottle files

    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: $(set_formula_name.formula)-bottle-$(artifact_name)
        targetPath: $(Build.ArtifactStagingDirectory)
      displayName: Publish formula-bottle-$(artifact_name)
