# File: azure-templates/brew_test_bot.yml

parameters:
  name: ''
  displayName: ''
  vmImage: ''
  xcode: ''

jobs:

- job: ${{ parameters.name }}
  displayName: "${{ parameters.displayName }}"

  pool:
    vmImage: ${{ parameters.vmImage }}

  dependsOn: []

  variables:
    xcode_version: ${{ parameters.xcode }}
    artifact_name: ${{ parameters.vmImage }}

  steps:

    - template: setup-homebrew-env.yml
      parameters:
        xcode: $(xcode_version)

    - bash: |
        echo UPSTREAM_GIT_URL:      $(UPSTREAM_GIT_URL)
        echo UPSTREAM_PULL_REQUEST: $(UPSTREAM_PULL_REQUEST)
        brew test-bot --root-url=$(bintray_root_url)
      displayName: Run brew test-bot
      env:
        UPSTREAM_GIT_URL: $(UPSTREAM_GIT_URL)
        UPSTREAM_PULL_REQUEST: $(UPSTREAM_PULL_REQUEST)

    - script: |
        FORMULA="$(ls *.bottle.json | sed 's/--.*//g')"
        echo "Formula name is: $FORMULA"
        echo "##vso[task.setvariable variable=formula;isOutput=true]$FORMULA"
      displayName: Set formula variable
      name: set_formula_name

    - bash: |
        cp *.bottle.* $(Build.ArtifactStagingDirectory)
      displayName: Copy json & bottle files for $(set_formula_name.formula)

    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: $(set_formula_name.formula)-bottle-$(artifact_name)
        targetPath: $(Build.ArtifactStagingDirectory)
      displayName: Publish $(set_formula_name.formula)-bottle-$(artifact_name)
