# File: templates/brew_test_bot.yml

parameters:
  name: ''
  displayName: ''
  vmImage: ''
  xcode: ''

jobs:

- job: ${{ parameters.name }}
  displayName: "${{ parameters.displayName }}"

  pool:
    vmImage: ${{ parameters.vmImage }}

  dependsOn: []

  variables:
    xcode_version: ${{ parameters.xcode }}
    artifact_name: ${{ parameters.vmImage }}

  steps:

    - bash: |
        set -e
        sudo xcode-select --switch /Applications/$(xcode_version).app/Contents/Developer
        brew update-reset /usr/local/Homebrew
        HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/$(github_user)/$(github_repo)"
        mkdir -p "$HOMEBREW_TAP_DIR"
        rm -rf "$HOMEBREW_TAP_DIR"
        ln -s "$PWD" "$HOMEBREW_TAP_DIR"
        brew tap --full $(test_bot_repo)
        git log --graph --decorate --oneline
      displayName: Setup environment

    - bash: |
        echo UPSTREAM_GIT_URL:      $(UPSTREAM_GIT_URL)
        echo UPSTREAM_PULL_REQUEST: $(UPSTREAM_PULL_REQUEST)
        brew test-bot --root-url=$(bintray_root_url)
      displayName: Run brew test-bot
      env:
        UPSTREAM_GIT_URL: $(UPSTREAM_GIT_URL)
        UPSTREAM_PULL_REQUEST: $(UPSTREAM_PULL_REQUEST)

    - script: |
        FORMULA="$(ls *.bottle.json | sed 's/--.*//g')"
        echo "Formula name is: $FORMULA"
        echo '##vso[task.setvariable variable=formula]$FORMULA'
      displayName: Set formula variable

    - bash: |
        cp *.bottle.* $(Build.ArtifactStagingDirectory)
      displayName: Copy json & bottle files

    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: $(formula)-bottle-$(artifact_name)
        targetPath: $(Build.ArtifactStagingDirectory)
      displayName: Publish $(formula)-bottle-$(artifact_name)
