# File: templates/brew_test_bot.yml

parameters:
  name: ''
  displayName: ''
  vmImage: ''
  xcode: ''

jobs:

- job: ${{ parameters.name }}
  displayName: "${{ parameters.displayName }}"

  pool:
    vmImage: ${{ parameters.vmImage }}

  dependsOn: []

  variables:
    xcode_version: ${{ parameters.xcode }}
    artifact_name: ${{ parameters.vmImage }}
    artifact_json: $(artifact_name).bottle.json
    artifact_bottle: $(artifact_name).bottle.tar.gz

  steps:
    # - bash: |
    #     echo "Install SSH Key"
    #   displayName: Install SSH Key

    - bash: |
        echo 'puts ENV["$(System.PullRequest.PullRequestNumber)"]' | ruby
      #   set -e
      #   sudo xcode-select --switch /Applications/$(xcode_version).app/Contents/Developer
      #   brew update
      #   HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/ladislas/homebrew-hello-world"
      #   mkdir -p "$HOMEBREW_TAP_DIR"
      #   rm -rf "$HOMEBREW_TAP_DIR"
      #   ln -s "$PWD" "$HOMEBREW_TAP_DIR"
      # displayName: Setup environment

    # - bash: |
    #     brew test-bot Formula/*.rb --root-url=$(bintray_root_url)
    #   displayName: Run brew test-bot

    # - bash: |
    #     cp *.bottle.* $(Build.ArtifactStagingDirectory)
    #   displayName: Copy json & bottle files

    # - task: PublishPipelineArtifact@0
    #   inputs:
    #     artifactName: $(artifact_prefix)-$(artifact_name)
    #     targetPath: $(Build.ArtifactStagingDirectory)
    #   displayName: Publish $(artifact_prefix)-$(artifact_name)
