# File: templates/brew_test_bot_ci_upload.yml

parameters:
  name: ''

jobs:

- job: brew_test_bot_ci_upload
  displayName: Upload bottles

  pool:
    vmImage: macOS-10.14

  steps:
    - bash: |
        echo "Install SSH Key"
        HOMEBREW_NO_AUTO_UPDATE=1 brew install tree
      displayName: Install SSH Key

    - task: DownloadPipelineArtifact@1
      inputs:
        itemPattern: '**'
        downloadPath: $(System.DefaultWorkingDirectory)
      displayName: Download artifacts

    - bash: |
        tree
        mv $(artifact_prefix)-*/* ./
        rm -rf $(artifact_prefix)-*
        cat *.json
        tree
        echo "Running brew test-bot --ci-upload"
      displayName: Run brew test-bot --ci-upload
